name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.16, 1.18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download && go test -race ./...
